amanager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from tasks import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'tasks', views.TaskView, 'task')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('tasks.urls', namespace='tasks')),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

backend/task_tracking/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.staticfiles import views

urlpatterns = [
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    from django.urls import re_path

    urlpatterns += [re_path(r"^static/(?P<path>.*)$", views.serve)]

tasks/urls.py
from .views import (
    TaskViewGeneric,
    upload_csv,
)
from django.urls import path

app_name = 'post'

urlpatterns =[
    path('', TaskViewGeneric.as_view(), name='task'),
    path('csv', upload_csv, name='csv'),
]

backend/src/models.py
from datetime import date
from typing import Optional, List

from sqlmodel import Field, SQLModel, Relationship

from src.database import engine


def create_db_schema():
    SQLModel.metadata.create_all(engine)


class ModelTableMixin(SQLModel):
    id: Optional[int] = Field(default=None, primary_key=True)


class ModelReadMixin(SQLModel):
    id: int


########################################################################################################################
# Company
########################################################################################################################
class CompanyBase(SQLModel):
    name: str = Field(index=True, unique=True)
    tasks: List["Task"] = Relationship(back_populates="company")


class Company(CompanyBase, ModelTableMixin, table=True):
    pass


class CompanyCreate(CompanyBase):
    pass


class CompanyRead(CompanyBase, ModelReadMixin):
    pass


class CompanyUpdate(SQLModel):
    name: Optional[str] = None


########################################################################################################################
# Person
########################################################################################################################
class PersonBase(SQLModel):
    name: str
    email: str = Field(index=True, unique=True)
    tasks: List["Task"] = Relationship(back_populates="created_by")


class Person(PersonBase, ModelTableMixin, table=True):
    pass


class PersonCreate(PersonBase):
    pass


class PersonRead(ModelReadMixin, PersonBase):
    pass


class PersonUpdate(SQLModel):
    name: Optional[str] = None
    email: Optional[str] = None


########################################################################################################################
# TaskStatus
########################################################################################################################
class TaskStatusBase(SQLModel):
    __tablename__ = "task_status"
    name: str = Field(index=True, unique=True)


class TaskStatus(TaskStatusBase, ModelTableMixin, table=True):
    pass


class TaskStatusCreate(TaskStatusBase):
    pass


class TaskStatusRead(ModelReadMixin, TaskStatusBase):
    pass


class TaskStatusUpdate(SQLModel):
    name: Optional[str] = None


########################################################################################################################
# Task
########################################################################################################################
class TaskBase(SQLModel):
    owner_id: int = Field(foreign_key="person.id")
    owner: Person = Relationship(back_populates="tasks")
    task_date: date
    description: str = Field(max_length=1000)
    company_id: int = Field(foreign_key="company.id")
    company: Company = Relationship(back_populates="tasks")
    status_id: int = Field(foreign_key="task_status.id")
    status: TaskStatus = Relationship(back_populates="tasks")


class Task(TaskBase, ModelTableMixin, table=True):
    pass


class TaskCreate(TaskBase):
    pass


class TaskRead(ModelReadMixin, TaskBase):
    pass


class TaskUpdate(SQLModel):
    task_date: Optional[date] = None
    description: Optional[str] = None
    company_id: Optional[int] = None
    status_id: Optional[int] = None

backend/task_tracking/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Task(models.Model):
    APPROVE = 'AP'
    IN_REVIEW = 'IR'
    REJECTED = 'RJ'

    STATUSES = [
        (APPROVE, 'Approve'),
        (IN_REVIEW, 'In review'),
        (REJECTED, 'Rejected'),
    ]

    owner = models.CharField(
        verbose_name=_("owner"),
        max_length=55,
    )
    email = models.EmailField(
        verbose_name=_("email"),
    )
    company_name = models.CharField(
        verbose_name=_("company_name"),
        max_length=55,
    )
    date = models.DateField()
    description = models.TextField(max_length=1000)
    status = models.CharField(
        max_length=2,
        default=IN_REVIEW,
    )

    class Meta:
        db_table = "tasks"
        verbose_name = "Task"
        verbose_name_plural = "Tasks"

    def __str__(self) -> str:
        return self.description

tasks/models.py
import datetime
from django.db import models

class Task(models.Model):
    STATUS_CHOICES = [
        ('IN_REVIEW','IN_REVIEW'),
        ('APPROVED','APPROVED'),
        ('REJECTED','REJECTED'),
    ]
    description = models.CharField(max_length=1000)
    created_by = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    completed_by = models.DateField(blank=True)
    company = models.CharField(max_length=255)
    status = models.CharField(max_length=255, default='2', choices=STATUS_CHOICES)
    timestamp = models.DateField(default=datetime.datetime.now, blank=True)
    
    def __str__(self):
        return self.description

tasks/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views import generic
from rest_framework import viewsets
from .serializers import TaskSerializer
from .models import Task


class TaskView(viewsets.ModelViewSet):
    serializer_class = TaskSerializer
    queryset = Task.objects.all().order_by('-status')
    

class TaskViewGeneric(generic.ListView):
    paginate_by = 25
    template_name = 'tasks/tasks.html'
    context_object_name = 'tasks'
    
    def get_queryset(self):
        return Task.objects.all().order_by('-status')


# TODO Raise messages instead of fail silently in all exceptions.
def upload_csv(request):
    if "GET" == request.method:
        return HttpResponseRedirect(reverse('tasks:task'))
    if "POST" == request.method:
        try:
            csv_file = request.FILES['upload-csv']
            if not csv_file.name.endswith('.csv'):
                return HttpResponseRedirect(reverse('tasks:task'))
            if csv_file.multiple_chunks():
                return HttpResponseRedirect(reverse('tasks:task'))
            file_data = csv_file.read().decode("utf-8")		

            lines = file_data.split("\n")
            for line in lines[1:]:
                fields = line.split(",")
                data_dict = {}
                data_dict['created_by'] = fields[0]
                data_dict['email'] = fields[1]
                data_dict['company'] = fields[2]
                data_dict['completed_by'] = fields[3]
                data_dict['description'] = fields[4]
                data_dict['status'] = fields[5]
                try:
                    Task.objects.create(**data_dict)			
                except Exception:
                    pass
            return HttpResponseRedirect(reverse('tasks:task'))
        except Exception:
            return HttpResponseRedirect(reverse('tasks:task'))

tasks/templates/tasks/tasks.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden m-8">
  <div class="container py-8 mx-auto">
  <div class="flex flex-wrap items-center border-b -mt-2">
    <div class="w-1/2">
      <h1 class="font-bold text-3xl">Task Manager</h1>
    </div>
    <form id="csv-form" onchange="submit();" class="w-1/2 flex justify-end" action="{% url 'tasks:csv'%}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <label class="relative rounded shadow-md bg-cyan-500 m-4 px-8 py-2 text-white z-10 cursor-pointer hover:bg-cyan-700 ease-in-out duration-200" for="upload-csv">
        UPLOAD CSV
        <svg id='csv-loading' class="animate-spin hidden absolute left-2.5 top-2.5 -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
      </label>
      <input class="opacity-0 absolute -z-1" name="upload-csv" type="file" id="upload-csv" accept=".csv">
    </form>
  </div>
    <div class="flex flex-col mt-2">
      <div class="shadow overflow-auto h-[550px]">
        <div class="py-2 inline-block min-w-full px-8">
          <div class="overflow-hidden">
            <table class="table-fixed min-w-full">
              <thead class="border-b text-sm font-medium text-gray-700 text-left">
                <tr>
                  <th scope="col" class="px-6 py-4">
                    CREATED BY
                  </th>
                  <th scope="col" class="px-6 py-4">
                    EMAIL
                  </th>
                  <th scope="col" class="px-6 py-4">
                    TASK DATE
                  </th>
                  <th scope="col" class="px-6 py-4">
                    TASK DESCRIPTION
                  </th>
                  <th scope="col" class="px-6 py-4">
                    COMPANY NAME
                  </th>
                  <th scope="col" class="px-6 py-4">
                    TASK STATUS
                  </th>
                </tr>
              </thead>
              <tbody>
              {% for task in tasks %}
              <tr class="bg-white border-b">
                <td class="px-6 py-4 text-sm font-medium text-gray-900">
                  {{task.created_by}}
                </td>
                <td class="text-sm text-gray-900 font-light px-6 py-4">
                  {{task.email}}
                </td>
                <td class="text-sm text-gray-900 font-light px-6 py-4">
                  {{task.completed_by|date:'Y-m-d'}}
                </td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 w-30">
                  {{task.description}}
                </td>
                <td class="text-sm text-gray-900 font-light px-6 py-4">
                  {{task.company}}
                </td>
                <td class="text-sm text-gray-900 font-light px-6 py-4">
                  {{task.status}}
                </td>
              </tr>
              {% endfor %}
              </tbody>

            </table>
          </div>
        </div>
        <div class="pagination text-center p-10 w-full">
          <span class="step-links bg-gray-100 rounded p-4">
              {% if page_obj.has_previous %}
                  <a class="p-2 border rounded hover:bg-gray-200 ease-in-out duration-200" href="?page=1">&laquo; first</a>
                  <a class="p-2 border rounded hover:bg-gray-200 ease-in-out duration-200" href="?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current p-2">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>

              {% if page_obj.has_next %}
                  <a class="p-2 border rounded hover:bg-gray-200 ease-in-out duration-200" href="?page={{ page_obj.next_page_number }}">next</a>
                  <a class="p-2 border rounded hover:bg-gray-200 ease-in-out duration-200" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
          </span>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
    {% tailwind_css %}
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>